# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://yong-cai.github.io/
baseurl: /
title: Yong Cai's Webpage
author: Yong Cai
description: Personal blog and resume
avatar: 
email: yourname@email.com
#github: jekyller/sustain # username
#twitter: username
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1

# co-authors
ivancanay: https://sites.northwestern.edu/iac879/
deborahkim: https://sites.google.com/view/deborahkim/
azeemshaikh: https://home.uchicago.edu/~amshaikh/

# needed for travis-ci build
exclude: [vendor]

